name: Deploy to Firebase
on:
  push:
    branches: [ main, dev ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.8.x'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      env:
        REACT_APP_SECRET_HOST_HEADER: ${{ secrets.SECRET_HOST_HEADER }}
        REACT_APP_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}