name: pytest

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pytest
      run: |
        pytest
      env:
        OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY  }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        SECRET_HOST_HEADER: ${{ secrets.SECRET_HOST_HEADER }}
        CSRF_SECRET_KEY: ${{ secrets.CSRF_SECRET_KEY }}
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}